name = "website3"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "canteen-db"
database_id = "b8c4a37f-2a23-42cc-b063-301628c98625"
